#!/bin/bash

echo "Analysis master"


# echo "06"
#python 06_bins_after_Delphes.py "$1"       ## Apply the analysis over "experimental" data


##Set variables, get raw data from .hepmc and rewrites them adding observables z_origin and t_gamma

# echo "01 analisis full"

# echo "01_analisis_PTselection_4.py"
# python 01_analisis_PTselection_4.py

# echo "01_analisis_PTselection_5.py"
# python 01_analisis_PTselection_5.py

# echo "01_analisis_PTselection_6.py"
# python 01_analisis_PTselection_6.py

## Run the modified Delphes through .hepmc

#  echo "02"
# python 02_run_Delphes.py "$3" "$2"

## Extract important data from .root generated by Delphes

# echo "03 basic"
# python 03_basic_root.py

 echo "04 basic analysis"
#python 04a_concat.py             #pickle merging
#python 04x_reduce.py             #Only if needed, reduce number of events
python 04c_deltaReflow.py         #Plot deltaR for eflowPhotons and eflowTracks

# echo "06 full"
#python 06_bins_after_Delphes_full.py "$1"



#compare
#python comparehepmc.py
#python comparewrite.py

#!final

#python comparewriteoptm.py

#python comparehepmc_new.py
#python comparewrite.py
# echo "07"
#python 07_making_graphs.py
# echo "07a"
#python "07a_making_graphs (copy).py"
# echo "07a_alpha_it"
#python 07a_making_graphs-copy-_alpha_it.py

# echo "09"
#python 09_contour_graphs.py