#!/bin/bash

echo "Analysis master"


##Set variables, get raw data from .hepmc and rewrites them adding observables z_origin and t_gamma
 echo "01 analisis full"
python 01_making_opt_hepmc.py

## Run the modified Delphes through .hepmc
 echo "02"
python 02_run_Delphes.py "$3" "$2"

## Extract important data from .root generated by Delphes with jet constituents
 echo "03 final info extraction"
python 03_extracting_root.py

#!Start of debugging
#The following code was constructed to review the analysis and debugging. It can be ignored for a more direct approach and skip to 04_bins_after_Delphes.py
#python 04c_deltaReflow.py         #Plot deltaR for eflowPhotons and eflowTracks
#!Finish of debugging

## Apply the analysis over "experimental" data
 echo "04 bins after Delphes"
python 04_bins_after_Delphes.py "$1"

 echo "05 Validation graphs"
python 05a_validation_graphs.py

#Calculate the Branching Ratio

#!no use
# echo "06"
# python 06_s95_graphs.py

 echo "07 Contour plots"
python 07_contour_graphs.py